spring:
  kafka:
    bootstrap-servers: ${KAFKA_BROKER}

    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
bot:
  name: ${BOT_NAME}
  token: ${BOT_TOKEN}
server:
  port: ${SERVER_PORT}
management:
  endpoints:
    web:
      exposure:
        include: prometheus, metrics, health
  endpoint:
    prometheus:
      enabled: true
  metrics:
    enable:
      all: true