name: Build and Push Docker Images

on:
  push:
    branches: [ master, main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin

      - name: Build bot-service project with Maven
        working-directory: ./backend
        run: mvn clean install

      - name: List files in bot-service target
        run: ls -la ./backend/target/

      - name: Build and Push bot-service Docker image
        run: |
          docker build -t $DOCKER_USER/service-forbot-kafka-docker:latest ./backend
          docker push $DOCKER_USER/service-forbot-kafka-docker:latest

      - name: Build telegram-bot project with Maven
        working-directory: ./bot
        run: mvn clean install

      - name: List files in telegram-bot target
        run: ls -la ./bot/target/

      - name: Build and Push telegram-bot Docker image
        run: |
          docker build -t $DOCKER_USER/telegrambot-kafka-deploy:latest ./bot
          docker push $DOCKER_USER/telegrambot-kafka-deploy:latest